services:
  - type: web
    name: punjab-rishta
    runtime: node
    plan: free
    buildCommand: npm install && node server/seed.js && node server/seed-more.js && node server/seed-females.js
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        value: 806692116297-tvo0mmiire2auq4nsrbubmo1uuh1gekh.apps.googleusercontent.com
