require("dotenv").config();
const db = require("./db");

const profiles = [
  // ═══ PATIALA (more) ═══
  { fullName: "Kamalpreet Kaur Bal", gender: "female", dob: "2001-05-20", heightCm: 162, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Bal", education: "Post Graduate (MA/MSc/MCom)", profession: "PCS Officer (Probation)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "Cleared PPSC in first attempt. MA Public Administration from Punjabi University. State-level athlete.", hobbies: "Athletics, Debate, Current Affairs", fatherName: "Sardar Balbir Singh Bal", fatherOccupation: "Block Development Officer (Retd)", motherName: "Sardarni Manjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Bank PO)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Tripuri, Patiala", phone: "9814331100", email: "kamalpreet.bal@gmail.com", whatsapp: "9814331100", partnerPref: "IAS/IPS/PCS or Doctor. Tall, well-educated. Age 27-33. Punjab.", consent: true, privacyLevel: "registered" },
  { fullName: "Ramandeep Kaur Sekhon", gender: "female", dob: "2002-08-10", heightCm: 157, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Sekhon", education: "Graduate (BA/BSc/BCom)", profession: "Studying for UPSC", incomeAnnual: "Not Working", complexion: "Very Fair", about: "BSc Hons from Thapar. Preparing for UPSC at Chandigarh coaching. Very studious and disciplined.", hobbies: "Reading, Debates, Mock Parliament, Chess", fatherName: "Sardar Lakhwinder Singh Sekhon", fatherOccupation: "Advocate (District Court Patiala)", motherName: "Sardarni Harpal Kaur", motherOccupation: "School Principal", siblings: "Only Child", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Model Town, Patiala", phone: "9876112244", email: "ramandeep.sekhon@gmail.com", whatsapp: "9876112244", partnerPref: "IAS/IPS aspirant or already in services. Intellectual match. Age 25-30.", consent: true, privacyLevel: "registered" },
  { fullName: "Harjinder Kaur Kalsi", gender: "female", dob: "1997-01-25", heightCm: 160, city: "Nabha", district: "Patiala", religion: "Sikh", community: "Ramgarhia", subcaste: "Kalsi", education: "Diploma", profession: "ITI Instructor", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "Diploma in Electronics. Working as ITI instructor in Nabha. Self-made, independent woman.", hobbies: "Electronics, Stitching, Cooking", fatherName: "Sardar Harbhajan Singh Kalsi", fatherOccupation: "Electrician (Own Shop)", motherName: "Sardarni Paramjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Plumber in Canada), 1 Sister (Married)", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Nabha, Patiala", phone: "9815442211", email: "harjinder.kalsi@gmail.com", whatsapp: "9815442211", partnerPref: "Working boy, govt or private. Ramgarhia preferred. Simple family. Age 26-32.", consent: true, privacyLevel: "registered" },
  { fullName: "Sukhmani Kaur Romana", gender: "female", dob: "2000-06-14", heightCm: 165, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Saini", subcaste: "Romana", education: "BDS", profession: "Dentist (Private Clinic)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "BDS from GDC Patiala. Running own dental clinic near Leela Bhawan. Active in NSS and dental camps.", hobbies: "Dentistry, Social Work, Bhangra, Cooking", fatherName: "Sardar Mohinder Singh Romana", fatherOccupation: "Fruit Commission Agent", motherName: "Sardarni Kuldeep Kaur", motherOccupation: "ANM (Govt)", siblings: "1 Brother (MBBS Student), 1 Sister (Married)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Urban Estate Phase 2, Patiala", phone: "9872553300", email: "dr.sukhmani.romana@gmail.com", whatsapp: "9872553300", partnerPref: "Doctor/Dentist/Engineer. Saini or Jat Sikh. Age 26-32. Punjab or abroad.", consent: true, privacyLevel: "registered" },
  { fullName: "Jaspreet Singh Dhindsa", gender: "male", dob: "1996-10-08", heightCm: 179, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhindsa", education: "MBA", profession: "Bank Manager (SBI)", incomeAnnual: "15-25 Lakh", complexion: "Wheatish", about: "MBA Finance from Punjabi University. Cleared IBPS PO, now Branch Manager at SBI Patiala.", hobbies: "Cricket, Finance, Gurudwara Sewa", fatherName: "Sardar Gurbachan Singh Dhindsa", fatherOccupation: "Retired Teacher", motherName: "Sardarni Baljit Kaur", motherOccupation: "Homemaker", siblings: "2 Sisters (Both Married)", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Tripuri Town, Patiala", phone: "9814664400", email: "jaspreet.dhindsa.sbi@gmail.com", whatsapp: "9814664400", partnerPref: "Graduate girl, homely. Govt job preferred. Age 22-27. Patiala district.", consent: true, privacyLevel: "registered" },

  // ═══ LUDHIANA (more) ═══
  { fullName: "Tania Wadhwa", gender: "female", dob: "2001-01-18", heightCm: 163, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Khatri", subcaste: "Wadhwa", education: "B.Tech / B.E.", profession: "Product Manager (Zomato)", incomeAnnual: "15-25 Lakh", complexion: "Very Fair", about: "B.Tech from BITS Pilani. Working as Product Manager at Zomato Gurgaon. Born and raised in Ludhiana.", hobbies: "Tech, Food Blogging, Yoga, Travel", fatherName: "Sh. Deepak Wadhwa", fatherOccupation: "Cycle Parts Manufacturer", motherName: "Smt. Meenakshi Wadhwa", motherOccupation: "Interior Designer", siblings: "1 Sister (NIFT Student)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Sarabha Nagar, Ludhiana", phone: "9876557700", email: "tania.wadhwa@gmail.com", whatsapp: "9876557700", partnerPref: "IIT/IIM/BITS alumnus. Tech or business. Open-minded family. Age 26-32. Metro city.", consent: true, privacyLevel: "registered" },
  { fullName: "Navjot Kaur Bains", gender: "female", dob: "1999-09-12", heightCm: 166, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Jat Sikh", subcaste: "Bains", education: "Post Graduate (MA/MSc/MCom)", profession: "Assistant Professor (GNE College)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "M.Sc Chemistry with NET qualified. Teaching at GNE Ludhiana. Research-oriented mind.", hobbies: "Research, Teaching, Reading, Kirtan", fatherName: "Sardar Pargat Singh Bains", fatherOccupation: "Farmer (35 acres) + Dairy", motherName: "Sardarni Surinder Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both NRI — UK)", familyType: "Joint", familyStatus: "Rich", familyCity: "Village Machhiwara, Ludhiana", phone: "9815668800", email: "navjot.bains.prof@gmail.com", whatsapp: "9815668800", partnerPref: "Well-educated professional. Professor/Doctor/Engineer. Sikh. Age 27-33. India or UK.", consent: true, privacyLevel: "registered" },
  { fullName: "Palak Singla", gender: "female", dob: "2000-04-30", heightCm: 155, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Agarwal", subcaste: "Singla", education: "Graduate (BA/BSc/BCom)", profession: "Interior Designer (Self-employed)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "B.Sc Interior Design. Running own design studio on Ferozepur Road. Modern, creative, independent.", hobbies: "Interior Design, Photography, Cooking, Instagram", fatherName: "Sh. Rakesh Singla", fatherOccupation: "Readymade Garments Trader", motherName: "Smt. Kavita Singla", motherOccupation: "Homemaker", siblings: "1 Brother (MBA, Family Business)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Dugri, Ludhiana", phone: "9872779900", email: "palak.singla.design@gmail.com", whatsapp: "9872779900", partnerPref: "Businessman or professional from Aggarwal/Mahajan/Singla family. Age 25-31.", consent: true, privacyLevel: "registered" },
  { fullName: "Gurleen Kaur Rai", gender: "female", dob: "2001-12-05", heightCm: 170, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Rai Sikh", subcaste: "Rai", education: "Nursing", profession: "Staff Nurse (DMCH Ludhiana)", incomeAnnual: "2-5 Lakh", complexion: "Wheatish", about: "BSc Nursing from DMCH. Compassionate nurse. From humble farming background. First graduate in family.", hobbies: "Patient Care, Cooking, Gardening, Village Life", fatherName: "Sardar Balwinder Singh Rai", fatherOccupation: "Small Farmer (5 acres)", motherName: "Sardarni Sharanjit Kaur", motherOccupation: "Farm Labour", siblings: "3 Sisters (1 Married, 2 Studying)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Mullanpur, Ludhiana", phone: "9814881100", email: "gurleen.rai.nurse@gmail.com", whatsapp: "9814881100", partnerPref: "Working boy from any Sikh community. Simple family. No dowry demands. Age 24-30.", consent: true, privacyLevel: "registered" },
  { fullName: "Karan Dhir", gender: "male", dob: "1997-06-22", heightCm: 177, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Arora", subcaste: "Dhir", education: "B.Tech / B.E.", profession: "Startup Founder (EdTech)", incomeAnnual: "25-50 Lakh", complexion: "Fair", about: "B.Tech from GNDEC. Founded an EdTech startup with 50K+ users. Y-Combinator finalist.", hobbies: "Startups, Cricket, Podcasts, Gym", fatherName: "Sh. Ashok Dhir", fatherOccupation: "Textile Exporter", motherName: "Smt. Renu Dhir", motherOccupation: "Homemaker", siblings: "1 Sister (Married, Canada)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Civil Lines, Ludhiana", phone: "9876990011", email: "karan.dhir.startup@gmail.com", whatsapp: "9876990011", partnerPref: "Smart, ambitious girl. B.Tech/MBA. Open to working wife. Age 23-28.", consent: true, privacyLevel: "registered" },

  // ═══ AMRITSAR (more) ═══
  { fullName: "Jasmeet Kaur Dhami", gender: "female", dob: "2000-11-28", heightCm: 164, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhami", education: "MBBS / MD", profession: "Doctor (SGRD Hospital)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "MBBS from SGRD Amritsar. Doing residency in Pediatrics. Loves children and community work.", hobbies: "Pediatrics, Giddha, Cooking Amritsari Food", fatherName: "Sardar Kulwant Singh Dhami", fatherOccupation: "Retired DSP", motherName: "Sardarni Rajwinder Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Army Major)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Ranjit Avenue, Amritsar", phone: "9815776600", email: "dr.jasmeet.dhami@gmail.com", whatsapp: "9815776600", partnerPref: "Doctor or IAS/PCS. Religious family. Height 5'10\"+. Age 27-33.", consent: true, privacyLevel: "registered" },
  { fullName: "Harleen Kaur Johal", gender: "female", dob: "2001-07-09", heightCm: 168, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Johal", education: "Graduate (BA/BSc/BCom)", profession: "Air Hostess (Air India)", incomeAnnual: "10-15 Lakh", complexion: "Very Fair", about: "BCom from GNDU. Selected as cabin crew for Air India. Tall, graceful, well-spoken.", hobbies: "Travel, Fashion, Languages, Fitness", fatherName: "Sardar Tarlochan Singh Johal", fatherOccupation: "NRI (UK — Restaurant Chain)", motherName: "Sardarni Kuldeep Kaur Johal", motherOccupation: "Homemaker", siblings: "1 Brother (MBA, UK)", familyType: "Nuclear", familyStatus: "Affluent", familyCity: "GT Road, Amritsar / London", phone: "9872881100", email: "harleen.johal.fly@gmail.com", whatsapp: "9872881100", partnerPref: "Professionally settled NRI or India-based. Business or corporate. Height 5'11\"+. Age 26-32.", consent: true, privacyLevel: "registered" },
  { fullName: "Aarav Chadha", gender: "male", dob: "1998-03-17", heightCm: 174, city: "Amritsar", district: "Amritsar", religion: "Hindu", community: "Khatri", subcaste: "Chadha", education: "MBA", profession: "Restaurant Chain Owner", incomeAnnual: "50 Lakh+", complexion: "Fair", about: "MBA from Symbiosis. Running 4 Amritsari food restaurants across Punjab. Food is passion and profession.", hobbies: "Cooking, Food Photography, Cricket, Gym", fatherName: "Sh. Sunil Chadha", fatherOccupation: "Retired Army Officer", motherName: "Smt. Poonam Chadha", motherOccupation: "Homemaker", siblings: "1 Sister (Married, Delhi)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Lawrence Road, Amritsar", phone: "9814993300", email: "aarav.chadha@gmail.com", whatsapp: "9814993300", partnerPref: "Graduate girl. Foodie, fun-loving. Good family values. Age 22-27. Any caste welcome.", consent: true, privacyLevel: "registered" },

  // ═══ JALANDHAR (more) ═══
  { fullName: "Amanpreet Kaur Sohal", gender: "female", dob: "1999-02-14", heightCm: 159, city: "Jalandhar", district: "Jalandhar", religion: "Sikh", community: "Jat Sikh", subcaste: "Sohal", education: "LLB / LLM", profession: "Advocate (Punjab & Haryana High Court)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "LLM from GNDU. Practicing in Punjab & Haryana High Court Chandigarh. Women's rights activist.", hobbies: "Law, Women Empowerment, Reading, Badminton", fatherName: "Sardar Karamjit Singh Sohal", fatherOccupation: "Senior Advocate", motherName: "Sardarni Jaswinder Kaur", motherOccupation: "Retired Bank Manager", siblings: "1 Brother (Civil Judge)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Model Town, Jalandhar", phone: "9876114400", email: "amanpreet.sohal.adv@gmail.com", whatsapp: "9876114400", partnerPref: "Advocate or IAS/PCS. Progressive family. Age 27-33. Punjab/Chandigarh.", consent: true, privacyLevel: "registered" },
  { fullName: "Simran Chawla", gender: "female", dob: "2001-10-21", heightCm: 161, city: "Jalandhar", district: "Jalandhar", religion: "Hindu", community: "Arora", subcaste: "Chawla", education: "B.Tech / B.E.", profession: "iOS Developer (Apple — Remote)", incomeAnnual: "25-50 Lakh", complexion: "Very Fair", about: "B.Tech from NIT Jalandhar. Working remotely for Apple as iOS developer. Tech geek with Punjabi heart.", hobbies: "Coding, Apple Products, Travel, Cooking", fatherName: "Sh. Sanjay Chawla", fatherOccupation: "Sports Goods Exporter", motherName: "Smt. Neha Chawla", motherOccupation: "Boutique Owner", siblings: "1 Brother (Studying in USA)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Urban Estate, Jalandhar", phone: "9815225500", email: "simran.chawla.dev@gmail.com", whatsapp: "9815225500", partnerPref: "Tech professional. IIT/NIT preferred. Open-minded. Age 26-32. Metro city or NRI.", consent: true, privacyLevel: "registered" },
  { fullName: "Sahil Bhatia", gender: "male", dob: "1997-08-04", heightCm: 176, city: "Jalandhar", district: "Jalandhar", religion: "Hindu", community: "Arora", subcaste: "Bhatia", education: "MBA", profession: "Sports Goods Exporter", incomeAnnual: "50 Lakh+", complexion: "Fair", about: "MBA from ISB. Running family's sports goods export to 30+ countries. National level Hockey player.", hobbies: "Hockey, Business, International Travel, Cars", fatherName: "Sh. Naresh Bhatia", fatherOccupation: "Sports Goods Manufacturer", motherName: "Smt. Sunita Bhatia", motherOccupation: "Homemaker", siblings: "1 Sister (Doctor, USA)", familyType: "Joint", familyStatus: "Affluent", familyCity: "BMC Chowk, Jalandhar", phone: "9872336600", email: "sahil.bhatia.exports@gmail.com", whatsapp: "9872336600", partnerPref: "Educated, cultured girl. MBA/Doctor. Sports-loving family is bonus. Age 22-27.", consent: true, privacyLevel: "registered" },

  // ═══ BATHINDA (more) ═══
  { fullName: "Sahibjeet Kaur Hundal", gender: "female", dob: "2000-03-28", heightCm: 163, city: "Bathinda", district: "Bathinda", religion: "Sikh", community: "Jat Sikh", subcaste: "Hundal", education: "Graduate (BA/BSc/BCom)", profession: "Clerk (Punjab Govt — DC Office)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BSc from Bathinda. Selected through PSSSB. Working at DC office. Hard-working and sincere.", hobbies: "Cooking, Gardening, GK, Gurudwara Visits", fatherName: "Sardar Hardev Singh Hundal", fatherOccupation: "Farmer (25 acres) + Fertilizer Agency", motherName: "Sardarni Jasbir Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Studying B.Tech)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Rampura, Bathinda", phone: "9814557700", email: "sahibjeet.hundal@gmail.com", whatsapp: "9814557700", partnerPref: "Govt job boy. Army/Police/Banking preferred. Jat Sikh. Age 25-31. Malwa region.", consent: true, privacyLevel: "registered" },
  { fullName: "Mandeep Kaur Sidhu", gender: "female", dob: "1998-12-15", heightCm: 158, city: "Bathinda", district: "Bathinda", religion: "Sikh", community: "Jat Sikh", subcaste: "Sidhu", education: "B.Ed / M.Ed", profession: "Govt Teacher (SSA)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "M.Ed from MRSPTU. Teaching under SSA scheme. From agricultural family. Believes in education for all.", hobbies: "Teaching, Farming, Social Work", fatherName: "Sardar Joga Singh Sidhu", fatherOccupation: "Farmer (40 acres)", motherName: "Sardarni Daljit Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both Farming), 1 Sister (Nurse)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Goniana, Bathinda", phone: "9876228800", email: "mandeep.sidhu.bath@gmail.com", whatsapp: "9876228800", partnerPref: "Farmer or govt job boy. Malwa belt. Joint family welcome. Age 26-33.", consent: true, privacyLevel: "registered" },

  // ═══ MOHALI / CHANDIGARH TRICITY ═══
  { fullName: "Gagandeep Kaur Khangura", gender: "female", dob: "1999-04-20", heightCm: 167, city: "Mohali", district: "Mohali (SAS Nagar)", religion: "Sikh", community: "Jat Sikh", subcaste: "Khangura", education: "M.Tech / M.E.", profession: "Data Scientist (Infosys BPM)", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "M.Tech AI/ML from PEC Chandigarh. Working in data science. Published 3 research papers.", hobbies: "Machine Learning, Reading, Yoga, Travel", fatherName: "Sardar Avtar Singh Khangura", fatherOccupation: "Retired Army Brigadier", motherName: "Sardarni Ranjit Kaur", motherOccupation: "Professor (PU)", siblings: "1 Brother (IIT Bombay Student)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Phase 5, Mohali", phone: "9815339900", email: "gagandeep.khangura@gmail.com", whatsapp: "9815339900", partnerPref: "IIT/NIT/BITS alumnus. Tech/Research/IAS. Age 27-33. Tricity or metro city.", consent: true, privacyLevel: "registered" },
  { fullName: "Ritika Malhotra", gender: "female", dob: "2001-09-08", heightCm: 160, city: "Zirakpur", district: "Mohali (SAS Nagar)", religion: "Hindu", community: "Khatri", subcaste: "Malhotra", education: "Graduate (BA/BSc/BCom)", profession: "HR Executive (Quark Media)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BBA from Chitkara University. Working in HR at Quark. Energetic, people-oriented personality.", hobbies: "Dancing, HR, Social Media, Cooking", fatherName: "Sh. Rajesh Malhotra", fatherOccupation: "Property Dealer", motherName: "Smt. Sunita Malhotra", motherOccupation: "Homemaker", siblings: "1 Brother (CA Intern)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "VIP Road, Zirakpur", phone: "9872440011", email: "ritika.malhotra.hr@gmail.com", whatsapp: "9872440011", partnerPref: "MBA/B.Tech professional. Earning 10L+. Tricity preferred. Age 25-31.", consent: true, privacyLevel: "registered" },

  // ═══ MOGA ═══
  { fullName: "Jagdeep Kaur Chahal", gender: "female", dob: "2000-07-15", heightCm: 162, city: "Moga", district: "Moga", religion: "Sikh", community: "Jat Sikh", subcaste: "Chahal", education: "B.Tech / B.E.", profession: "Junior Engineer (PSPCL)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "B.Tech Electrical from SLIET Longowal. Selected as JE in PSPCL. Strong and independent.", hobbies: "Electronics, Kabaddi, Cooking, Reading", fatherName: "Sardar Nirmal Singh Chahal", fatherOccupation: "Farmer (30 acres)", motherName: "Sardarni Gurmeet Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Canada — PR)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Dharamkot, Moga", phone: "9814775500", email: "jagdeep.chahal.je@gmail.com", whatsapp: "9814775500", partnerPref: "Govt job — SDO/JE/Banking. Jat Sikh. Good farming family. Age 26-32.", consent: true, privacyLevel: "registered" },

  // ═══ KAPURTHALA ═══
  { fullName: "Harleen Kaur Bhatti", gender: "female", dob: "2001-11-30", heightCm: 164, city: "Kapurthala", district: "Kapurthala", religion: "Sikh", community: "Lubana", subcaste: "Bhatti", education: "Post Graduate (MA/MSc/MCom)", profession: "Bank PO (Punjab National Bank)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "MCom from Kapurthala. Cleared IBPS PO. Posted in Kapurthala branch. Honest and hardworking.", hobbies: "Banking, Cooking, Gurudwara Visits, Reading", fatherName: "Sardar Gurtej Singh Bhatti", fatherOccupation: "Transport Business", motherName: "Sardarni Manpreet Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both in Transport Business)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Kapurthala City", phone: "9876332200", email: "harleen.bhatti.pnb@gmail.com", whatsapp: "9876332200", partnerPref: "Govt job or businessman. Sikh family. Age 25-31. Doaba region preferred.", consent: true, privacyLevel: "registered" },

  // ═══ GURDASPUR ═══
  { fullName: "Rupinder Kaur Samra", gender: "female", dob: "1999-05-25", heightCm: 166, city: "Gurdaspur", district: "Gurdaspur", religion: "Sikh", community: "Jat Sikh", subcaste: "Samra", education: "MBBS / MD", profession: "Medical Officer (PHC)", incomeAnnual: "10-15 Lakh", complexion: "Very Fair", about: "MBBS from GMC Amritsar. Serving as Medical Officer at Primary Health Center near border area.", hobbies: "Rural Healthcare, Cooking, Travel, Music", fatherName: "Sardar Jagtar Singh Samra", fatherOccupation: "Retired Army Havildar", motherName: "Sardarni Kulwinder Kaur", motherOccupation: "ASHA Worker", siblings: "1 Brother (BSF Constable)", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Batala, Gurdaspur", phone: "9815884400", email: "dr.rupinder.samra@gmail.com", whatsapp: "9815884400", partnerPref: "Doctor or Army/BSF officer. Punjab based. Simple family. Age 27-34.", consent: true, privacyLevel: "registered" },

  // ═══ FEROZEPUR ═══
  { fullName: "Prabhjot Kaur Randhawa", gender: "female", dob: "2000-09-18", heightCm: 160, city: "Ferozepur", district: "Ferozepur", religion: "Sikh", community: "Jat Sikh", subcaste: "Randhawa", education: "Graduate (BA/BSc/BCom)", profession: "Constable (Punjab Police)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "BA from Ferozepur. Selected in Punjab Police. National level Kho-Kho player. Strong and disciplined.", hobbies: "Sports, Fitness, Farming, Cooking", fatherName: "Sardar Daljit Singh Randhawa", fatherOccupation: "Farmer (20 acres)", motherName: "Sardarni Kulwant Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both Army)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Makhu, Ferozepur", phone: "9872115500", email: "prabhjot.randhawa.police@gmail.com", whatsapp: "9872115500", partnerPref: "Army/Police/Govt job. Sporty family. Malwa or Majha. Age 25-31.", consent: true, privacyLevel: "registered" },

  // ═══ SANGRUR (more) ═══
  { fullName: "Harpreet Kaur Multani", gender: "female", dob: "2001-04-12", heightCm: 158, city: "Malerkotla", district: "Malerkotla", religion: "Sikh", community: "Saini", subcaste: "Multani", education: "Diploma", profession: "Pharmacist (Govt Hospital)", incomeAnnual: "2-5 Lakh", complexion: "Fair", about: "D.Pharmacy from Sangrur. Working at Civil Hospital Malerkotla. Quiet, sincere, spiritual.", hobbies: "Pharmacy, Gardening, Gurbani, Cooking", fatherName: "Sardar Jagdev Singh Multani", fatherOccupation: "Vegetable Vendor", motherName: "Sardarni Harjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (ITI Student), 2 Sisters", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Malerkotla", phone: "9814996600", email: "harpreet.multani@gmail.com", whatsapp: "9814996600", partnerPref: "Working boy, any govt or private job. Simple family. No dowry. Age 24-30.", consent: true, privacyLevel: "registered" },

  // ═══ HOSHIARPUR (more) ═══
  { fullName: "Mannat Kaur Dhugga", gender: "female", dob: "2002-01-10", heightCm: 170, city: "Hoshiarpur", district: "Hoshiarpur", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhugga", education: "B.Tech / B.E.", profession: "Software Developer (Amazon — Bangalore)", incomeAnnual: "25-50 Lakh", complexion: "Very Fair", about: "B.Tech CS from NIT Jalandhar. Working at Amazon Bangalore. NRI family with strong Punjab roots.", hobbies: "Coding, Travel, Photography, Bhangra", fatherName: "Sardar Sukhdev Singh Dhugga", fatherOccupation: "NRI (Canada — Trucking Business)", motherName: "Sardarni Amandeep Kaur", motherOccupation: "Homemaker (Canada)", siblings: "1 Brother (Studying MS in USA)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Hoshiarpur / Brampton, Canada", phone: "9876771100", email: "mannat.dhugga@gmail.com", whatsapp: "9876771100", partnerPref: "Software Engineer or Doctor. NIT/IIT. Canada/USA/India. Height 5'10\"+. Age 25-30.", consent: true, privacyLevel: "registered" },

  // ═══ MUKTSAR ═══
  { fullName: "Jaswinder Kaur Brar", gender: "female", dob: "1998-08-22", heightCm: 161, city: "Sri Muktsar Sahib", district: "Muktsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Brar", education: "B.Ed / M.Ed", profession: "Govt Teacher (High School)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "M.Ed from MRSPTU. Teaching Science at Govt High School Muktsar. Passionate about rural education.", hobbies: "Teaching, Science Experiments, Social Work, Cooking", fatherName: "Sardar Sucha Singh Brar", fatherOccupation: "Farmer (35 acres) + Commission Agent", motherName: "Sardarni Balwinder Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Married, Farming)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Muktsar City", phone: "9815117700", email: "jaswinder.brar.mukt@gmail.com", whatsapp: "9815117700", partnerPref: "Govt job or farmer with good land. Malwa region. Age 26-33.", consent: true, privacyLevel: "registered" },

  // ═══ MORE MALES ═══
  { fullName: "Harvinder Singh Virk", gender: "male", dob: "1996-04-14", heightCm: 182, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Jat Sikh", subcaste: "Virk", education: "MBBS / MD", profession: "Orthopedic Surgeon (DMC Hospital)", incomeAnnual: "25-50 Lakh", complexion: "Fair", about: "MS Ortho from CMC Ludhiana. Senior consultant. National level swimmer. Well-settled.", hobbies: "Surgery, Swimming, Cricket, Farming", fatherName: "Sardar Jagjit Singh Virk", fatherOccupation: "Farmer (60 acres) + Rice Mill", motherName: "Sardarni Narinder Kaur", motherOccupation: "Homemaker", siblings: "1 Sister (Married, USA)", familyType: "Joint", familyStatus: "Affluent", familyCity: "Khanna, Ludhiana", phone: "9814003355", email: "dr.harvinder.virk@gmail.com", whatsapp: "9814003355", partnerPref: "Doctor or professional girl. Jat Sikh. Fair, 5'4\"+. Age 24-29.", consent: true, privacyLevel: "registered" },
  { fullName: "Navtej Singh Randhawa", gender: "male", dob: "1997-12-01", heightCm: 180, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Randhawa", education: "LLB / LLM", profession: "Civil Judge (Junior Division)", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "LLM from GNDU. Cleared PCS-J exam. Youngest Civil Judge in district. Very principled.", hobbies: "Law, Reading, Chess, Gurudwara Sewa", fatherName: "Sardar Balkar Singh Randhawa", fatherOccupation: "Retired SP (Police)", motherName: "Sardarni Jaswinder Kaur", motherOccupation: "Retired Lecturer", siblings: "1 Sister (MBBS, PGI)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Ranjit Avenue, Amritsar", phone: "9876449900", email: "navtej.randhawa.judge@gmail.com", whatsapp: "9876449900", partnerPref: "Advocate or Doctor. Intellectual match. Sikh. Age 23-28. Punjab/Chandigarh.", consent: true, privacyLevel: "registered" },
  { fullName: "Rohit Sood", gender: "male", dob: "1998-02-28", heightCm: 173, city: "Mohali", district: "Mohali (SAS Nagar)", religion: "Hindu", community: "Brahmin", subcaste: "Sood", education: "M.Tech / M.E.", profession: "AI Research Scientist (IIT Ropar)", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "PhD candidate at IIT Ropar in AI/ML. Published 8 papers. TEDx speaker. Science communicator.", hobbies: "AI Research, TEDx, Piano, Hiking", fatherName: "Sh. Suresh Sood", fatherOccupation: "Retired Professor (PU)", motherName: "Smt. Anita Sood", motherOccupation: "Retired Teacher", siblings: "1 Sister (Data Scientist, USA)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Sector 15, Chandigarh", phone: "9872558800", email: "rohit.sood.ai@gmail.com", whatsapp: "9872558800", partnerPref: "Highly educated girl. PhD/M.Tech/MBBS. Intellectual curiosity a must. Age 24-29.", consent: true, privacyLevel: "registered" },
];

let count = 0;
for (const p of profiles) {
  db.createProfile(p);
  count++;
}
console.log(`Seeded ${count} additional profiles.`);
