require("dotenv").config();
const db = require("./db");

const profiles = [
  // ═══ PATIALA ═══
  { fullName: "Lovepreet Kaur Aulakh", gender: "female", dob: "2001-02-18", heightCm: 164, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Aulakh", education: "B.Tech / B.E.", profession: "Software Engineer (HCL)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "B.Tech CSE from Thapar University. Working at HCL Noida. Wants to settle back in Punjab.", hobbies: "Coding, Bhangra, Travel, Cooking", fatherName: "Sardar Sukhpal Singh Aulakh", fatherOccupation: "Inspector (Punjab Police)", motherName: "Sardarni Jasmeet Kaur", motherOccupation: "Govt School Teacher", siblings: "1 Sister (MBA Student)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Urban Estate Phase 1, Patiala", phone: "9814220033", email: "lovepreet.aulakh@gmail.com", whatsapp: "9814220033", partnerPref: "B.Tech/MBA/CA boy. Punjab-based or willing to return. Age 26-31.", consent: true, privacyLevel: "registered" },
  { fullName: "Jaspreet Kaur Bhullar", gender: "female", dob: "2000-08-24", heightCm: 159, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Bhullar", education: "Graduate (BA/BSc/BCom)", profession: "SSC CGL (Tax Assistant)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BCom from Govt Mohindra College. Cleared SSC CGL, posted as Tax Assistant. Very disciplined.", hobbies: "Current Affairs, Yoga, Cooking, Gurudwara", fatherName: "Sardar Boota Singh Bhullar", fatherOccupation: "Retired Postmaster", motherName: "Sardarni Kiranjit Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both in Army)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Tripuri Town, Patiala", phone: "9876330055", email: "jaspreet.bhullar.ssc@gmail.com", whatsapp: "9876330055", partnerPref: "Central/State govt job. Sikh. Age 25-31. Punjab or Chandigarh.", consent: true, privacyLevel: "registered" },
  { fullName: "Amritpal Kaur Dhillon", gender: "female", dob: "1999-03-09", heightCm: 168, city: "Samana", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhillon", education: "Nursing", profession: "Nursing Officer (AIIMS Delhi)", incomeAnnual: "10-15 Lakh", complexion: "Very Fair", about: "MSc Nursing. Working at AIIMS New Delhi. State gold medalist in nursing. Very tall and graceful.", hobbies: "Healthcare, Fitness, Punjabi Music, Reading", fatherName: "Sardar Mohinder Singh Dhillon", fatherOccupation: "Farmer (22 acres)", motherName: "Sardarni Amarjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Studying MBBS)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Samana, Patiala", phone: "9815441100", email: "amritpal.dhillon.nurse@gmail.com", whatsapp: "9815441100", partnerPref: "Doctor/Engineer/Govt job. Tall 5'10\"+. Jat Sikh. Age 26-32. Delhi or Punjab.", consent: true, privacyLevel: "registered" },
  { fullName: "Rupinder Kaur Pannu", gender: "female", dob: "2002-06-12", heightCm: 156, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Saini", subcaste: "Pannu", education: "12th Pass", profession: "Beautician (Own Salon)", incomeAnnual: "2-5 Lakh", complexion: "Wheatish", about: "Running own beauty salon near Leela Bhawan. Self-employed since 18. Creative and hardworking.", hobbies: "Makeup, Mehndi, Cooking, Singing", fatherName: "Sardar Gurnam Singh Pannu", fatherOccupation: "Auto Rickshaw Driver", motherName: "Sardarni Rajwant Kaur", motherOccupation: "Domestic Worker", siblings: "1 Brother (ITI — Electrician), 2 Sisters", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Old Patiala", phone: "9872660044", email: "rupinder.pannu@gmail.com", whatsapp: "9872660044", partnerPref: "Working boy from any background. Simple, caring. No dowry. Age 23-29.", consent: true, privacyLevel: "registered" },

  // ═══ LUDHIANA ═══
  { fullName: "Manpreet Kaur Samra", gender: "female", dob: "2000-05-28", heightCm: 165, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Jat Sikh", subcaste: "Samra", education: "CA / CS / ICWA", profession: "CA (Big 4 — EY)", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "CA from ICAI. Working at Ernst & Young Gurgaon. Ludhiana girl at heart. Top of her batch.", hobbies: "Finance, Travel, Gym, Cooking Punjabi Food", fatherName: "Sardar Paramjit Singh Samra", fatherOccupation: "Cloth Merchant (Wholesale)", motherName: "Sardarni Diljit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Studying CA)", familyType: "Joint", familyStatus: "Rich", familyCity: "Model Town Extension, Ludhiana", phone: "9814550077", email: "manpreet.samra.ca@gmail.com", whatsapp: "9814550077", partnerPref: "CA/MBA/Doctor from business family. Age 27-33. Ludhiana or metro city.", consent: true, privacyLevel: "registered" },
  { fullName: "Sonia Narang", gender: "female", dob: "2001-10-14", heightCm: 158, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Arora", subcaste: "Narang", education: "B.Tech / B.E.", profession: "DevOps Engineer (Infosys)", incomeAnnual: "10-15 Lakh", complexion: "Very Fair", about: "B.Tech IT from GNDEC. Cloud computing specialist. AWS certified. Modern girl with traditional values.", hobbies: "Cloud Tech, Yoga, Painting, Reading", fatherName: "Sh. Vikram Narang", fatherOccupation: "Hosiery Dyer (Factory Owner)", motherName: "Smt. Rani Narang", motherOccupation: "Homemaker", siblings: "1 Sister (Fashion Designer)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "BRS Nagar, Ludhiana", phone: "9876442200", email: "sonia.narang.devops@gmail.com", whatsapp: "9876442200", partnerPref: "IT professional. B.Tech/MCA. Age 26-31. Open to relocation.", consent: true, privacyLevel: "registered" },
  { fullName: "Harleen Kaur Dhaliwal", gender: "female", dob: "1998-12-01", heightCm: 170, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhaliwal", education: "MBA", profession: "Manager (HDFC Bank)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "MBA Finance from Punjabi University. Working as Branch Manager at HDFC. Ambitious and dedicated.", hobbies: "Banking, Reading, Bollywood, Fitness", fatherName: "Sardar Baljinder Singh Dhaliwal", fatherOccupation: "Retired Tehsildar", motherName: "Sardarni Manpreet Kaur", motherOccupation: "Retired Teacher", siblings: "1 Brother (Software Engineer, Canada)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Sarabha Nagar, Ludhiana", phone: "9815663300", email: "harleen.dhaliwal.hdfc@gmail.com", whatsapp: "9815663300", partnerPref: "Bank officer/MBA/CA. Jat Sikh. Age 28-34. Punjab or Chandigarh.", consent: true, privacyLevel: "registered" },
  { fullName: "Neha Goyal", gender: "female", dob: "2001-07-22", heightCm: 155, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Agarwal", subcaste: "Goyal", education: "Graduate (BA/BSc/BCom)", profession: "Fashion Boutique Owner", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BCom from SCD Govt College. Running successful bridal boutique on Pakhowal Road. Creative entrepreneur.", hobbies: "Fashion Design, Bridal Makeup, Instagram, Cooking", fatherName: "Sh. Manoj Goyal", fatherOccupation: "Sweet Shop Owner (Chain)", motherName: "Smt. Pushpa Goyal", motherOccupation: "Homemaker", siblings: "1 Brother (Running Sweet Shop)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Dugri, Ludhiana", phone: "9872774400", email: "neha.goyal.boutique@gmail.com", whatsapp: "9872774400", partnerPref: "Businessman from Aggarwal/Goyal family. Age 25-30. Ludhiana preferred.", consent: true, privacyLevel: "registered" },

  // ═══ AMRITSAR ═══
  { fullName: "Simranjeet Kaur Sandhu", gender: "female", dob: "2000-01-30", heightCm: 166, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Sandhu", education: "Post Graduate (MA/MSc/MCom)", profession: "IELTS Trainer (Self-employed)", incomeAnnual: "5-10 Lakh", complexion: "Very Fair", about: "MA English from GNDU. Running own IELTS coaching center near Hall Gate. Band 8.5 scorer.", hobbies: "English Literature, Teaching, Travel, Cooking", fatherName: "Sardar Ranjit Singh Sandhu", fatherOccupation: "NRI (Canada — Real Estate)", motherName: "Sardarni Kulwinder Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Canada — PR)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Ranjit Avenue, Amritsar / Surrey, Canada", phone: "9815772200", email: "simranjeet.sandhu.ielts@gmail.com", whatsapp: "9815772200", partnerPref: "NRI (Canada/Australia/UK) or well-settled in India. Age 26-32.", consent: true, privacyLevel: "registered" },
  { fullName: "Diljot Kaur Gill", gender: "female", dob: "2001-04-05", heightCm: 162, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Gill", education: "MBBS / MD", profession: "MBBS Intern (GMC Amritsar)", incomeAnnual: "Not Working", complexion: "Fair", about: "Final year MBBS at GMC Amritsar. Topper. Planning MD Cardiology. Deeply spiritual, visits Darbar Sahib daily.", hobbies: "Medicine, Kirtan, Cooking, Swimming", fatherName: "Sardar Gurmail Singh Gill", fatherOccupation: "Advocate (Sessions Court)", motherName: "Sardarni Navneet Kaur", motherOccupation: "School Principal", siblings: "1 Sister (Studying BDS)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "GT Road, Amritsar", phone: "9872883300", email: "diljot.gill.mbbs@gmail.com", whatsapp: "9872883300", partnerPref: "Doctor (MD/MS). Religious Sikh. Tall. Age 27-33. India.", consent: true, privacyLevel: "registered" },

  // ═══ JALANDHAR ═══
  { fullName: "Priyanka Sachdeva", gender: "female", dob: "1999-11-17", heightCm: 160, city: "Jalandhar", district: "Jalandhar", religion: "Hindu", community: "Khatri", subcaste: "Sachdeva", education: "MBA", profession: "Marketing Head (Sports Brand)", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "MBA Marketing from IIM Lucknow. Heading marketing for a leading Jalandhar sports brand. Ambitious.", hobbies: "Marketing, Cricket, Travel, Reading", fatherName: "Sh. Ashish Sachdeva", fatherOccupation: "Leather Goods Exporter", motherName: "Smt. Nisha Sachdeva", motherOccupation: "Homemaker", siblings: "Only Child", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Model Town, Jalandhar", phone: "9814993311", email: "priyanka.sachdeva.iim@gmail.com", whatsapp: "9814993311", partnerPref: "IIM/ISB/IIT alumnus. Corporate job or own business. Age 27-33.", consent: true, privacyLevel: "registered" },
  { fullName: "Harleen Kaur Thiara", gender: "female", dob: "2002-03-20", heightCm: 167, city: "Jalandhar", district: "Jalandhar", religion: "Sikh", community: "Jat Sikh", subcaste: "Thiara", education: "Graduate (BA/BSc/BCom)", profession: "Sub Inspector (Punjab Police)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "BSc from DAV Jalandhar. Selected as Sub Inspector in Punjab Police. State-level athlete — 100m sprint.", hobbies: "Athletics, Fitness, Shooting, Cooking", fatherName: "Sardar Satnam Singh Thiara", fatherOccupation: "Farmer (18 acres)", motherName: "Sardarni Balbir Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (NDA Cadet)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Nakodar, Jalandhar", phone: "9876551100", email: "harleen.thiara.si@gmail.com", whatsapp: "9876551100", partnerPref: "Army/Police/Govt job. Sporty family. Jat Sikh. Age 25-31.", consent: true, privacyLevel: "registered" },

  // ═══ BATHINDA ═══
  { fullName: "Gurjot Kaur Dhillon", gender: "female", dob: "2000-09-08", heightCm: 163, city: "Bathinda", district: "Bathinda", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhillon", education: "B.Tech / B.E.", profession: "Engineer (HPCL Refinery)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "B.Tech Chemical from PEC Chandigarh. Working at HPCL Bathinda Refinery. First woman engineer in the unit.", hobbies: "Chemical Engineering, Fitness, Reading, Travel", fatherName: "Sardar Harpal Singh Dhillon", fatherOccupation: "Farmer (45 acres) + Cotton Ginning", motherName: "Sardarni Jasbir Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Studying B.Tech)", familyType: "Joint", familyStatus: "Rich", familyCity: "Village Talwandi Sabo, Bathinda", phone: "9815882200", email: "gurjot.dhillon.hpcl@gmail.com", whatsapp: "9815882200", partnerPref: "PSU/Govt engineer or IAS. Jat Sikh. Malwa region. Age 26-32.", consent: true, privacyLevel: "registered" },
  { fullName: "Harmanpreet Kaur Brar", gender: "female", dob: "2001-05-15", heightCm: 172, city: "Bathinda", district: "Bathinda", religion: "Sikh", community: "Jat Sikh", subcaste: "Brar", education: "Graduate (BA/BSc/BCom)", profession: "National Level Kabaddi Player", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "BSc Sports from Punjabi University. National Kabaddi player. Won gold at Nationals. Sports scholarship.", hobbies: "Kabaddi, Athletics, Farming, Fitness", fatherName: "Sardar Gurdev Singh Brar", fatherOccupation: "Farmer (30 acres)", motherName: "Sardarni Kuldeep Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both Kabaddi players)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Rampura Phul, Bathinda", phone: "9872993300", email: "harmanpreet.brar.kabaddi@gmail.com", whatsapp: "9872993300", partnerPref: "Army/Police or sportsperson. Strong build. Jat Sikh. Age 25-31. Malwa.", consent: true, privacyLevel: "registered" },

  // ═══ MOHALI ═══
  { fullName: "Aashna Grover", gender: "female", dob: "2001-08-10", heightCm: 163, city: "Mohali", district: "Mohali (SAS Nagar)", religion: "Hindu", community: "Khatri", subcaste: "Grover", education: "B.Tech / B.E.", profession: "UI/UX Designer (Freshworks)", incomeAnnual: "15-25 Lakh", complexion: "Very Fair", about: "B.Des from UIET Chandigarh. Working at Freshworks. Passionate about accessible design.", hobbies: "Design, Art, Piano, Yoga", fatherName: "Sh. Sanjeev Grover", fatherOccupation: "IT Company Owner", motherName: "Smt. Aarti Grover", motherOccupation: "Yoga Instructor", siblings: "1 Brother (Studying in USA)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Phase 7, Mohali", phone: "9814117700", email: "aashna.grover.ux@gmail.com", whatsapp: "9814117700", partnerPref: "Tech professional. Creative mind. Open family. Age 26-31. Tricity or metro.", consent: true, privacyLevel: "registered" },

  // ═══ SANGRUR ═══
  { fullName: "Mandeep Kaur Josan", gender: "female", dob: "1998-10-25", heightCm: 160, city: "Sangrur", district: "Sangrur", religion: "Sikh", community: "Jat Sikh", subcaste: "Josan", education: "Post Graduate (MA/MSc/MCom)", profession: "Veterinary Doctor (Govt)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BVSc & AH from GADVASU Ludhiana. Govt Veterinary Officer in Sangrur. From farming family.", hobbies: "Veterinary Science, Animals, Farming, Cooking", fatherName: "Sardar Baldev Singh Josan", fatherOccupation: "Farmer (28 acres) + Dairy Farm", motherName: "Sardarni Harjinder Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (MBBS Student)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Barnala Road, Sangrur", phone: "9876004400", email: "dr.mandeep.josan@gmail.com", whatsapp: "9876004400", partnerPref: "Doctor/Vet/Engineer with farming roots. Jat Sikh. Age 27-33. Malwa belt.", consent: true, privacyLevel: "registered" },

  // ═══ FAZILKA ═══
  { fullName: "Ravneet Kaur Sidhu", gender: "female", dob: "2000-12-08", heightCm: 161, city: "Fazilka", district: "Fazilka", religion: "Sikh", community: "Jat Sikh", subcaste: "Sidhu", education: "Graduate (BA/BSc/BCom)", profession: "BSF Constable", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "BSc from Fazilka. Selected in BSF. Serving at Indo-Pak border. Tough, patriotic, spirited.", hobbies: "Shooting, Fitness, Cooking, Patriotic Songs", fatherName: "Sardar Kartar Singh Sidhu", fatherOccupation: "Farmer (15 acres, Border Area)", motherName: "Sardarni Jaswinder Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both in Army)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village near Indo-Pak Border, Fazilka", phone: "9815115500", email: "ravneet.sidhu.bsf@gmail.com", whatsapp: "9815115500", partnerPref: "Army/BSF/CRPF or Police. Age 25-31. Punjab.", consent: true, privacyLevel: "registered" },

  // ═══ FATEHGARH SAHIB ═══
  { fullName: "Jasleen Kaur Shergill", gender: "female", dob: "2001-06-30", heightCm: 165, city: "Fatehgarh Sahib", district: "Fatehgarh Sahib", religion: "Sikh", community: "Jat Sikh", subcaste: "Shergill", education: "B.Ed / M.Ed", profession: "Govt School Teacher", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "M.Ed from Patiala. ETT Teacher at Govt Primary School. Loves teaching young children.", hobbies: "Teaching, Kids, Kirtan, Art & Craft", fatherName: "Sardar Jagjit Singh Shergill", fatherOccupation: "Granthi (Gurudwara)", motherName: "Sardarni Baljit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Studying B.Tech)", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Fatehgarh Sahib City", phone: "9872226600", email: "jasleen.shergill.teacher@gmail.com", whatsapp: "9872226600", partnerPref: "Religious Sikh. Govt job or own business. Simple family. Age 25-31.", consent: true, privacyLevel: "registered" },

  // ═══ PATHANKOT ═══
  { fullName: "Kirandeep Kaur Nanda", gender: "female", dob: "1999-09-15", heightCm: 162, city: "Pathankot", district: "Pathankot", religion: "Sikh", community: "Khatri", subcaste: "Nanda", education: "B.Tech / B.E.", profession: "Officer (Indian Railways — IRSE)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "B.Tech from NIT Hamirpur. Cleared UPSC Engineering Services. Railway officer posted at Pathankot.", hobbies: "Railways, Reading, Travel, Photography", fatherName: "Sardar Avtar Singh Nanda", fatherOccupation: "Retired Station Master", motherName: "Sardarni Gurmeet Kaur", motherOccupation: "Homemaker", siblings: "1 Sister (Doctor, Delhi)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Pathankot Cantt", phone: "9814884400", email: "kirandeep.nanda.irse@gmail.com", whatsapp: "9814884400", partnerPref: "IAS/IPS/IFS or IRSE/IRTS. Age 27-33. All-India.", consent: true, privacyLevel: "registered" },

  // ═══ TARN TARAN ═══
  { fullName: "Rajveer Kaur Dhanjal", gender: "female", dob: "2000-04-18", heightCm: 167, city: "Tarn Taran", district: "Tarn Taran", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhanjal", education: "MBBS / MD", profession: "Medical Officer (PHC Tarn Taran)", incomeAnnual: "10-15 Lakh", complexion: "Very Fair", about: "MBBS from GMC Amritsar. Serving border communities. Passionate about rural health.", hobbies: "Medicine, Sewa, Kirtan, Farming", fatherName: "Sardar Jagtar Singh Dhanjal", fatherOccupation: "Farmer (25 acres)", motherName: "Sardarni Sukhwinder Kaur", motherOccupation: "ASHA Worker", siblings: "1 Brother (BSF SI)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Tarn Taran City", phone: "9876339900", email: "dr.rajveer.dhanjal@gmail.com", whatsapp: "9876339900", partnerPref: "Doctor or IAS/PCS. Religious Sikh. Age 27-33. Punjab.", consent: true, privacyLevel: "registered" },

  // ═══ RUPNAGAR ═══
  { fullName: "Gurleen Kaur Multani", gender: "female", dob: "2001-11-12", heightCm: 159, city: "Rupnagar", district: "Rupnagar", religion: "Sikh", community: "Saini", subcaste: "Multani", education: "Graduate (BA/BSc/BCom)", profession: "Clerk (Punjab Govt — Tehsil Office)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BA from Rupnagar. Cleared PSSSB Clerk exam. Sincere and ambitious. Planning for PCS next.", hobbies: "Competitive Exams, Reading, Cooking, Yoga", fatherName: "Sardar Gurmukh Singh Multani", fatherOccupation: "Retired Army Subedar", motherName: "Sardarni Jaswinder Kaur", motherOccupation: "Homemaker", siblings: "1 Sister (Nursing Student)", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Anandpur Sahib, Rupnagar", phone: "9815007700", email: "gurleen.multani.rup@gmail.com", whatsapp: "9815007700", partnerPref: "Govt job. Sikh. Simple family. Age 25-30. Doaba or Tricity.", consent: true, privacyLevel: "registered" },

  // ═══ NAWANSHAHR ═══
  { fullName: "Harleen Kaur Pawar", gender: "female", dob: "2000-02-25", heightCm: 164, city: "Nawanshahr", district: "Nawanshahr", religion: "Sikh", community: "Ravidasia", subcaste: "Pawar", education: "B.Tech / B.E.", profession: "Software Developer (Wipro)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "B.Tech from Lovely Professional University. Working at Wipro Chandigarh. First engineer in family.", hobbies: "Coding, Education, Social Equality, Music", fatherName: "Sardar Jaswinder Singh Pawar", fatherOccupation: "Carpenter (Govt Workshop)", motherName: "Sardarni Balveer Kaur", motherOccupation: "Anganwadi Worker", siblings: "1 Brother (Studying Polytechnic), 1 Sister", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Nawanshahr City", phone: "9872448800", email: "harleen.pawar.dev@gmail.com", whatsapp: "9872448800", partnerPref: "Educated working boy. Progressive family. No caste discrimination. Age 24-30.", consent: true, privacyLevel: "registered" },

  // ═══ MANSA ═══
  { fullName: "Parveen Kaur Dhindsa", gender: "female", dob: "1998-07-20", heightCm: 158, city: "Mansa", district: "Mansa", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhindsa", education: "B.Ed / M.Ed", profession: "Headmistress (Govt Middle School)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "M.Ed. Promoted to Headmistress at 28. Active in adult education programs. Respected in village.", hobbies: "Teaching, Social Work, Farming, Cooking", fatherName: "Sardar Buta Singh Dhindsa", fatherOccupation: "Farmer (35 acres) + Sarpanch", motherName: "Sardarni Surjit Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Farming), 1 Sister (Married)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Budhlada, Mansa", phone: "9814668800", email: "parveen.dhindsa.mansa@gmail.com", whatsapp: "9814668800", partnerPref: "Farmer with good land or govt job. Jat Sikh. Malwa. Age 28-35.", consent: true, privacyLevel: "registered" },

  // ═══ BARNALA ═══
  { fullName: "Simran Kaur Cheema", gender: "female", dob: "2001-01-05", heightCm: 163, city: "Barnala", district: "Barnala", religion: "Sikh", community: "Jat Sikh", subcaste: "Cheema", education: "Nursing", profession: "Staff Nurse (Civil Hospital Barnala)", incomeAnnual: "2-5 Lakh", complexion: "Fair", about: "BSc Nursing from Barnala. Working at Civil Hospital. Compassionate and hardworking. Village girl.", hobbies: "Nursing, Cooking, Knitting, Gardening", fatherName: "Sardar Nachhatar Singh Cheema", fatherOccupation: "Small Farmer (8 acres)", motherName: "Sardarni Manjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Army Jawan), 2 Sisters", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Tapa, Barnala", phone: "9876115500", email: "simran.cheema.barnala@gmail.com", whatsapp: "9876115500", partnerPref: "Working boy. Army/Police preferred. Simple family. Age 24-30. Malwa.", consent: true, privacyLevel: "registered" },
];

let count = 0;
for (const p of profiles) {
  db.createProfile(p);
  count++;
}
console.log(`Seeded ${count} female-only profiles.`);
