require("dotenv").config();
const db = require("./db");

const profiles = [
  // ═══ PATIALA ═══
  { fullName: "Harleen Kaur Sidhu", gender: "female", dob: "2000-03-15", heightCm: 163, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Sidhu", education: "Graduate (BA/BSc/BCom)", profession: "Bank Clerk (PNB)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "Simple and family-oriented girl. Love cooking and reading Gurbani. Completed BA from Rajindra University.", hobbies: "Cooking, Reading, Gurbani Path", fatherName: "Sardar Balwant Singh Sidhu", fatherOccupation: "Farmer (25 acres)", motherName: "Sardarni Kulwinder Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Married, Army), 1 Sister (Married)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Ghanaur, Patiala", phone: "9814112200", email: "harleen.sidhu@gmail.com", whatsapp: "9814112200", partnerPref: "Looking for Jat Sikh boy, well-educated, preferably government job. Age 25-30. Punjab based.", consent: true, privacyLevel: "registered" },
  { fullName: "Manpreet Kaur Dhillon", gender: "female", dob: "1998-07-22", heightCm: 160, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhillon", education: "B.Ed / M.Ed", profession: "Government School Teacher", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "Working as ETT teacher in government school. Believes in simple living. Amritdhari family.", hobbies: "Teaching, Kirtan, Gardening", fatherName: "Sardar Jaswinder Singh Dhillon", fatherOccupation: "Retired SDO (Irrigation)", motherName: "Sardarni Paramjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Engineer, Chandigarh)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Model Town, Patiala", phone: "9876223311", email: "manpreet.dhillon.ptl@gmail.com", whatsapp: "9876223311", partnerPref: "Sikh boy from good family. Government job preferred. Non-drinker. Age 27-33.", consent: true, privacyLevel: "registered" },
  { fullName: "Simran Kaur Brar", gender: "female", dob: "2001-11-05", heightCm: 165, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Brar", education: "B.Tech / B.E.", profession: "Software Developer (Infosys)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "B.Tech from Thapar University Patiala. Working in Chandigarh IT Park. Modern yet rooted in Punjabi values.", hobbies: "Coding, Bhangra, Traveling, Photography", fatherName: "Sardar Gurdev Singh Brar", fatherOccupation: "Businessman (Transport)", motherName: "Sardarni Daljit Kaur", motherOccupation: "Homemaker", siblings: "1 Sister (Studying MBBS)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Urban Estate, Patiala", phone: "9815334422", email: "simran.brar.dev@gmail.com", whatsapp: "9815334422", partnerPref: "Well-educated professional, open-minded. B.Tech/MBA/Doctor preferred. Age 25-30. NRI also welcome.", consent: true, privacyLevel: "registered" },
  { fullName: "Gurleen Kaur Mann", gender: "female", dob: "1999-05-18", heightCm: 158, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Mann", education: "MBBS / MD", profession: "Doctor (Rajindra Hospital)", incomeAnnual: "15-25 Lakh", complexion: "Very Fair", about: "MBBS from GMC Patiala. Doing MD in Gynecology. Passionate about women's healthcare in rural Punjab.", hobbies: "Reading Medical Journals, Yoga, Music", fatherName: "Sardar Nachhatar Singh Mann", fatherOccupation: "Civil Surgeon (Retired)", motherName: "Dr. Harpreet Kaur Mann", motherOccupation: "Dentist (Private Clinic)", siblings: "1 Brother (IAS Officer)", familyType: "Nuclear", familyStatus: "Affluent", familyCity: "Civil Lines, Patiala", phone: "9872445533", email: "dr.gurleen.mann@gmail.com", whatsapp: "9872445533", partnerPref: "Doctor or IAS/IPS officer. Height 5'10\"+. Sikh family. Age 28-34. Based in India.", consent: true, privacyLevel: "registered" },
  { fullName: "Navneet Kaur Grewal", gender: "female", dob: "1997-09-30", heightCm: 162, city: "Rajpura", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Grewal", education: "MBA", profession: "HR Manager (Ambuja Cement)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "MBA from Punjabi University. Working in corporate sector. Well-traveled, independent thinker.", hobbies: "Traveling, Cooking, Fitness", fatherName: "Sardar Kulbir Singh Grewal", fatherOccupation: "Retired Army Colonel", motherName: "Sardarni Balbir Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Both Married)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Rajpura, Patiala", phone: "9814556644", email: "navneet.grewal@gmail.com", whatsapp: "9814556644", partnerPref: "Professionally settled boy. MBA/B.Tech. Corporate job or business. Age 28-35. Punjab/Chandigarh.", consent: true, privacyLevel: "registered" },
  { fullName: "Amandeep Kaur Sandhu", gender: "female", dob: "2000-01-12", heightCm: 167, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Sandhu", education: "Nursing", profession: "Staff Nurse (PGI Chandigarh)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "BSc Nursing from Government Nursing College Patiala. Working at PGI. Caring and compassionate.", hobbies: "Volunteering, Cooking, Gardening", fatherName: "Sardar Resham Singh Sandhu", fatherOccupation: "Farmer (15 acres)", motherName: "Sardarni Surjit Kaur", motherOccupation: "ASHA Worker", siblings: "2 Sisters (Both Married)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Nabha, Patiala", phone: "9876667755", email: "amandeep.sandhu.nurse@gmail.com", whatsapp: "9876667755", partnerPref: "Sikh boy, government job or Army. Simple family. Age 25-31. Punjab preferred.", consent: true, privacyLevel: "registered" },

  // ═══ LUDHIANA ═══
  { fullName: "Priya Aggarwal", gender: "female", dob: "1999-04-08", heightCm: 160, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Agarwal", subcaste: "Bansal", education: "CA / CS / ICWA", profession: "Chartered Accountant", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "CA from ICAI. Working with Deloitte Chandigarh. Ludhiana born and raised. Family into hosiery business.", hobbies: "Finance, Yoga, Bollywood", fatherName: "Sh. Rajesh Aggarwal", fatherOccupation: "Hosiery Manufacturer", motherName: "Smt. Sunita Aggarwal", motherOccupation: "Homemaker", siblings: "1 Brother (Managing family business)", familyType: "Joint", familyStatus: "Rich", familyCity: "Model Town, Ludhiana", phone: "9814778866", email: "priya.aggarwal.ca@gmail.com", whatsapp: "9814778866", partnerPref: "CA/MBA/Doctor from Aggarwal or Mahajan family. Business family preferred. Age 27-32.", consent: true, privacyLevel: "registered" },
  { fullName: "Jasleen Kaur Bajwa", gender: "female", dob: "2001-08-14", heightCm: 168, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Jat Sikh", subcaste: "Bajwa", education: "B.Tech / B.E.", profession: "Data Analyst (TCS)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "B.Tech CS from GNDEC Ludhiana. Working in IT sector. Loves tech and Punjabi culture equally.", hobbies: "Coding, Giddha, Photography, Travel", fatherName: "Sardar Harvinder Singh Bajwa", fatherOccupation: "Inspector (Punjab Police)", motherName: "Sardarni Jaswinder Kaur", motherOccupation: "Govt Teacher", siblings: "1 Sister (Studying MBA)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "BRS Nagar, Ludhiana", phone: "9876889977", email: "jasleen.bajwa@gmail.com", whatsapp: "9876889977", partnerPref: "Well-educated Sikh boy. IT professional or engineer. Age 25-30. India or abroad.", consent: true, privacyLevel: "registered" },
  { fullName: "Riya Mahajan", gender: "female", dob: "2000-12-25", heightCm: 157, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Mahajan", subcaste: "Gupta", education: "Post Graduate (MA/MSc/MCom)", profession: "Content Writer (Freelance)", incomeAnnual: "2-5 Lakh", complexion: "Wheatish", about: "MA English from PAU Ludhiana. Freelance content writer. Creative soul who loves literature and chai.", hobbies: "Writing, Reading, Poetry, Cooking", fatherName: "Sh. Vinod Mahajan", fatherOccupation: "Textile Trader", motherName: "Smt. Asha Mahajan", motherOccupation: "Homemaker", siblings: "1 Brother (CA)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Sarabha Nagar, Ludhiana", phone: "9815990088", email: "riya.mahajan.writer@gmail.com", whatsapp: "9815990088", partnerPref: "Educated boy who respects creativity. Graduate minimum. Good family values. Age 25-31.", consent: true, privacyLevel: "registered" },
  { fullName: "Harmandeep Kaur Dhaliwal", gender: "female", dob: "1998-03-10", heightCm: 170, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhaliwal", education: "MBBS / MD", profession: "Doctor (DMC Hospital)", incomeAnnual: "15-25 Lakh", complexion: "Very Fair", about: "MBBS from CMC Ludhiana. Working as Senior Resident in Medicine. Family-oriented yet career-driven.", hobbies: "Tennis, Cooking, Travel, Sewa", fatherName: "Sardar Baljinder Singh Dhaliwal", fatherOccupation: "Farmer (50 acres) + Transport Business", motherName: "Sardarni Ravinder Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Studying in Canada)", familyType: "Joint", familyStatus: "Affluent", familyCity: "Hambran Road, Ludhiana", phone: "9872001188", email: "dr.harmandeep@gmail.com", whatsapp: "9872001188", partnerPref: "Doctor/IAS/Engineer. Jat Sikh preferred. Height 5'11\"+. Settled in India or Canada. Age 28-34.", consent: true, privacyLevel: "registered" },
  { fullName: "Ananya Jindal", gender: "female", dob: "2001-06-20", heightCm: 162, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Arora", subcaste: "Jindal", education: "Graduate (BA/BSc/BCom)", profession: "Fashion Designer (Own Boutique)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "NIFT graduate. Running own boutique on Pakhowal Road. Creative and business-minded.", hobbies: "Fashion, Sketching, Bollywood Dance, Instagram", fatherName: "Sh. Sanjay Jindal", fatherOccupation: "Automobile Dealer", motherName: "Smt. Pooja Jindal", motherOccupation: "Housewife", siblings: "1 Sister (Studying Abroad)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Civil Lines, Ludhiana", phone: "9814112299", email: "ananya.jindal.fashion@gmail.com", whatsapp: "9814112299", partnerPref: "Well-settled businessman or professional. Open-minded family. Age 25-32. Any city.", consent: true, privacyLevel: "registered" },
  { fullName: "Sukhpreet Kaur Gill", gender: "female", dob: "1999-10-02", heightCm: 164, city: "Ludhiana", district: "Ludhiana", religion: "Sikh", community: "Ramgarhia", subcaste: "Gill", education: "Diploma", profession: "Lab Technician (SPS Hospital)", incomeAnnual: "2-5 Lakh", complexion: "Wheatish", about: "DMLT from Ludhiana. Working in pathology lab. Simple and hardworking girl from humble background.", hobbies: "Sewing, Cooking, Watching Punjabi Movies", fatherName: "Sardar Sukhwinder Singh Gill", fatherOccupation: "Welder (Factory)", motherName: "Sardarni Balwinder Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers, 1 Sister", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Focal Point, Ludhiana", phone: "9876334400", email: "sukhpreet.gill.ldh@gmail.com", whatsapp: "9876334400", partnerPref: "Simple Sikh boy, working. No dowry demands. Age 24-30. Ludhiana or nearby.", consent: true, privacyLevel: "registered" },

  // ═══ AMRITSAR ═══
  { fullName: "Kirandeep Kaur Bhullar", gender: "female", dob: "2000-02-28", heightCm: 161, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Bhullar", education: "Post Graduate (MA/MSc/MCom)", profession: "Lecturer (Khalsa College)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "MA Punjabi Literature. Teaching at Khalsa College Amritsar. Deeply spiritual, regular at Darbar Sahib.", hobbies: "Punjabi Poetry, Kirtan, Yoga", fatherName: "Sardar Harmeet Singh Bhullar", fatherOccupation: "Retired Subedar Major", motherName: "Sardarni Charanjit Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Own Business)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Ranjit Avenue, Amritsar", phone: "9815445566", email: "kirandeep.bhullar@gmail.com", whatsapp: "9815445566", partnerPref: "Religious Sikh boy. Government job or professor. Amritsar/Jalandhar. Age 27-33.", consent: true, privacyLevel: "registered" },
  { fullName: "Tamanna Sethi", gender: "female", dob: "2001-04-15", heightCm: 159, city: "Amritsar", district: "Amritsar", religion: "Hindu", community: "Khatri", subcaste: "Sethi", education: "MBA", profession: "Marketing Manager (Startup)", incomeAnnual: "10-15 Lakh", complexion: "Very Fair", about: "MBA from GNDU Amritsar. Working with a health-tech startup. Ambitious and driven.", hobbies: "Marketing, Social Media, Travel, Reading", fatherName: "Sh. Rakesh Sethi", fatherOccupation: "Gold Jeweler (Own Shop)", motherName: "Smt. Anita Sethi", motherOccupation: "Homemaker", siblings: "1 Brother (Jewelry Business)", familyType: "Joint", familyStatus: "Rich", familyCity: "Hall Bazaar, Amritsar", phone: "9872556677", email: "tamanna.sethi@gmail.com", whatsapp: "9872556677", partnerPref: "MBA/Professional from business family. Age 27-33. Amritsar or metro city.", consent: true, privacyLevel: "registered" },

  // ═══ JALANDHAR ═══
  { fullName: "Pavneet Kaur Randhawa", gender: "female", dob: "1999-12-10", heightCm: 166, city: "Jalandhar", district: "Jalandhar", religion: "Sikh", community: "Jat Sikh", subcaste: "Randhawa", education: "B.Tech / B.E.", profession: "Software Engineer (Wipro)", incomeAnnual: "10-15 Lakh", complexion: "Fair", about: "B.Tech from NIT Jalandhar. Working in Chandigarh. Sports lover — played state level hockey.", hobbies: "Hockey, Coding, Music, Travel", fatherName: "Sardar Davinder Singh Randhawa", fatherOccupation: "Sports Equipment Manufacturer", motherName: "Sardarni Kamalpreet Kaur", motherOccupation: "Principal (Govt School)", siblings: "1 Sister (CA)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Model Town, Jalandhar", phone: "9814667788", email: "pavneet.randhawa@gmail.com", whatsapp: "9814667788", partnerPref: "Engineer or Doctor. Sports-loving family. Height 5'10\"+. Age 26-32.", consent: true, privacyLevel: "registered" },
  { fullName: "Divya Kapoor", gender: "female", dob: "2000-08-03", heightCm: 155, city: "Jalandhar", district: "Jalandhar", religion: "Hindu", community: "Arora", subcaste: "Kapoor", education: "LLB / LLM", profession: "Advocate (District Court)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "LLB from DAV University Jalandhar. Practicing advocate. Passionate about justice and women's rights.", hobbies: "Reading Law, Debate, Social Work", fatherName: "Sh. Anil Kapoor", fatherOccupation: "Advocate (High Court)", motherName: "Smt. Neelam Kapoor", motherOccupation: "Homemaker", siblings: "1 Brother (Also Advocate)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Civil Lines, Jalandhar", phone: "9876778800", email: "divya.kapoor.adv@gmail.com", whatsapp: "9876778800", partnerPref: "Advocate or IAS/PCS. Educated family. Progressive outlook. Age 27-33.", consent: true, privacyLevel: "registered" },

  // ═══ BATHINDA ═══
  { fullName: "Rajwinder Kaur Boparai", gender: "female", dob: "1998-06-15", heightCm: 163, city: "Bathinda", district: "Bathinda", religion: "Sikh", community: "Jat Sikh", subcaste: "Boparai", education: "B.Ed / M.Ed", profession: "PET Teacher (Govt School)", incomeAnnual: "5-10 Lakh", complexion: "Wheatish", about: "M.Ed from Punjabi University. Government PET teacher. National level Kabaddi player.", hobbies: "Kabaddi, Athletics, Coaching, Farming", fatherName: "Sardar Amrik Singh Boparai", fatherOccupation: "Farmer (40 acres)", motherName: "Sardarni Surjit Kaur", motherOccupation: "Homemaker", siblings: "2 Brothers (Farming)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Rampura, Bathinda", phone: "9815889900", email: "rajwinder.boparai@gmail.com", whatsapp: "9815889900", partnerPref: "Army/Police/Govt job. Sporty family. Malwa region preferred. Age 26-32.", consent: true, privacyLevel: "registered" },

  // ═══ MOHALI ═══
  { fullName: "Ishita Sharma", gender: "female", dob: "2001-02-20", heightCm: 164, city: "Mohali", district: "Mohali (SAS Nagar)", religion: "Hindu", community: "Brahmin", subcaste: "Sharma", education: "B.Tech / B.E.", profession: "UX Designer (Google)", incomeAnnual: "25-50 Lakh", complexion: "Very Fair", about: "B.Des from UIET Chandigarh. Working as UX Designer at Google Bangalore. Tricity roots.", hobbies: "Design, Art, Yoga, Travel", fatherName: "Sh. Manoj Sharma", fatherOccupation: "Professor (PU Chandigarh)", motherName: "Smt. Reena Sharma", motherOccupation: "Principal (Govt School)", siblings: "Only Child", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Phase 3B2, Mohali", phone: "9872990011", email: "ishita.sharma.ux@gmail.com", whatsapp: "9872990011", partnerPref: "Well-educated professional in IT/Design. Open-minded family. Any caste. Age 26-32.", consent: true, privacyLevel: "registered" },

  // ═══ MALE PROFILES ═══
  { fullName: "Gurpreet Singh Gill", gender: "male", dob: "1997-11-25", heightCm: 180, city: "Patiala", district: "Patiala", religion: "Sikh", community: "Jat Sikh", subcaste: "Gill", education: "B.Tech / B.E.", profession: "Civil Engineer (Govt PWD)", incomeAnnual: "10-15 Lakh", complexion: "Wheatish", about: "B.Tech Civil from PEC Chandigarh. Working as SDO in PWD Punjab. Family-oriented and sincere.", hobbies: "Cricket, Farming, Cooking", fatherName: "Sardar Sukhdev Singh Gill", fatherOccupation: "Farmer (30 acres)", motherName: "Sardarni Charanjit Kaur", motherOccupation: "Homemaker", siblings: "1 Sister (Married, Doctor)", familyType: "Joint", familyStatus: "Upper Middle Class", familyCity: "Village Samana, Patiala", phone: "9814223355", email: "gurpreet.gill.sdo@gmail.com", whatsapp: "9814223355", partnerPref: "Graduate or professional girl. Homely and cultured. Jat Sikh preferred. Age 22-27.", consent: true, privacyLevel: "registered" },
  { fullName: "Arjun Bansal", gender: "male", dob: "1996-05-12", heightCm: 175, city: "Ludhiana", district: "Ludhiana", religion: "Hindu", community: "Agarwal", subcaste: "Bansal", education: "MBA", profession: "Businessman (Hosiery Export)", incomeAnnual: "50 Lakh+", complexion: "Fair", about: "MBA from ISB Hyderabad. Running family's hosiery export business. Annual turnover 15 Cr.", hobbies: "Golf, Travel, Cars, Business Networking", fatherName: "Sh. Satish Bansal", fatherOccupation: "Hosiery Manufacturer", motherName: "Smt. Meena Bansal", motherOccupation: "Homemaker", siblings: "1 Brother (Joint Business)", familyType: "Joint", familyStatus: "Affluent", familyCity: "Sarabha Nagar, Ludhiana", phone: "9876445500", email: "arjun.bansal.ldh@gmail.com", whatsapp: "9876445500", partnerPref: "Graduate girl from Aggarwal/Mahajan family. Homely, good values. Age 22-28.", consent: true, privacyLevel: "registered" },
  { fullName: "Lovepreet Singh Cheema", gender: "male", dob: "1998-09-08", heightCm: 183, city: "Amritsar", district: "Amritsar", religion: "Sikh", community: "Jat Sikh", subcaste: "Cheema", education: "MBBS / MD", profession: "Doctor (GMC Amritsar)", incomeAnnual: "15-25 Lakh", complexion: "Fair", about: "MBBS from GMC Amritsar. Doing MD Surgery. Tall, handsome, religious. Goes to Darbar Sahib daily.", hobbies: "Gatka, Gym, Kirtan, Reading", fatherName: "Sardar Teja Singh Cheema", fatherOccupation: "IAS Officer (Retired)", motherName: "Sardarni Hardip Kaur", motherOccupation: "Retired Principal", siblings: "1 Sister (Married, Canada)", familyType: "Nuclear", familyStatus: "Affluent", familyCity: "Mall Road, Amritsar", phone: "9815556688", email: "dr.lovepreet.cheema@gmail.com", whatsapp: "9815556688", partnerPref: "Doctor or highly educated girl. Religious Sikh family. Fair complexion. Height 5'4\"+. Age 23-28.", consent: true, privacyLevel: "registered" },
  { fullName: "Raghav Mittal", gender: "male", dob: "1997-01-30", heightCm: 172, city: "Jalandhar", district: "Jalandhar", religion: "Hindu", community: "Mahajan", subcaste: "Mittal", education: "CA / CS / ICWA", profession: "CA (Own Practice)", incomeAnnual: "25-50 Lakh", complexion: "Fair", about: "CA with own practice in Jalandhar. Handling 50+ clients. Sports equipment family business also.", hobbies: "Cricket, Finance, Movies, Cooking", fatherName: "Sh. Pawan Mittal", fatherOccupation: "Sports Equipment Manufacturer", motherName: "Smt. Kiran Mittal", motherOccupation: "Homemaker", siblings: "1 Sister (Married)", familyType: "Nuclear", familyStatus: "Rich", familyCity: "Model Town, Jalandhar", phone: "9872667700", email: "raghav.mittal.ca@gmail.com", whatsapp: "9872667700", partnerPref: "Graduate girl from Mahajan/Aggarwal family. Cultured and family-oriented. Age 22-27.", consent: true, privacyLevel: "registered" },
  { fullName: "Harjot Singh Virk", gender: "male", dob: "1999-07-18", heightCm: 178, city: "Bathinda", district: "Bathinda", religion: "Sikh", community: "Jat Sikh", subcaste: "Virk", education: "Graduate (BA/BSc/BCom)", profession: "Army Officer (Captain)", incomeAnnual: "10-15 Lakh", complexion: "Wheatish", about: "NDA graduate. Captain in Indian Army, posted at Bathinda Cantonment. 3rd generation Army family.", hobbies: "Shooting, Horse Riding, Fitness, Adventure", fatherName: "Col. Bikram Singh Virk (Retd)", fatherOccupation: "Retired Colonel", motherName: "Sardarni Dalbir Kaur", motherOccupation: "Homemaker", siblings: "1 Brother (Air Force Pilot)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Bathinda Cantt", phone: "9814778899", email: "harjot.virk.army@gmail.com", whatsapp: "9814778899", partnerPref: "Graduate girl. Ready for Army life. Brave and adaptable. Age 22-27. Any Sikh community.", consent: true, privacyLevel: "registered" },

  // ═══ MORE CITIES ═══
  { fullName: "Rupinder Kaur Aulakh", gender: "female", dob: "2000-10-05", heightCm: 161, city: "Sangrur", district: "Sangrur", religion: "Sikh", community: "Jat Sikh", subcaste: "Aulakh", education: "Graduate (BA/BSc/BCom)", profession: "Patwari (Revenue Dept)", incomeAnnual: "5-10 Lakh", complexion: "Fair", about: "BSc Agriculture from PAU. Working as Patwari in Sangrur. First in family to get govt job.", hobbies: "Agriculture, Cooking, Village Life", fatherName: "Sardar Buta Singh Aulakh", fatherOccupation: "Farmer (20 acres)", motherName: "Sardarni Gurbax Kaur", motherOccupation: "Homemaker", siblings: "2 Sisters (Both Studying)", familyType: "Joint", familyStatus: "Middle Class", familyCity: "Village Dhuri, Sangrur", phone: "9876001122", email: "rupinder.aulakh@gmail.com", whatsapp: "9876001122", partnerPref: "Government job boy. Simple family. Farmer family also welcome. Age 25-31.", consent: true, privacyLevel: "registered" },
  { fullName: "Komal Arora", gender: "female", dob: "2001-03-22", heightCm: 158, city: "Hoshiarpur", district: "Hoshiarpur", religion: "Hindu", community: "Arora", subcaste: "Arora", education: "Nursing", profession: "Nurse (Civil Hospital)", incomeAnnual: "2-5 Lakh", complexion: "Fair", about: "GNM from Hoshiarpur. Working at Civil Hospital. Gentle, caring, devoted to patients.", hobbies: "Cooking, Prayers, Knitting", fatherName: "Sh. Prem Arora", fatherOccupation: "Shopkeeper (Kirana Store)", motherName: "Smt. Kamla Arora", motherOccupation: "Homemaker", siblings: "1 Brother (Auto Driver), 1 Sister", familyType: "Nuclear", familyStatus: "Middle Class", familyCity: "Hoshiarpur City", phone: "9815223344", email: "komal.arora.hsp@gmail.com", whatsapp: "9815223344", partnerPref: "Working boy from any caste. Simple family. No dowry. Age 24-30. Punjab.", consent: true, privacyLevel: "registered" },
  { fullName: "Maninder Singh Dhillon", gender: "male", dob: "1996-12-14", heightCm: 176, city: "Mohali", district: "Mohali (SAS Nagar)", religion: "Sikh", community: "Jat Sikh", subcaste: "Dhillon", education: "M.Tech / M.E.", profession: "Software Architect (Infosys)", incomeAnnual: "25-50 Lakh", complexion: "Fair", about: "M.Tech from IIT Ropar. 7 years in tech. Leading a team of 20 at Infosys Chandigarh.", hobbies: "Tech, Cricket, Punjabi Music, Hiking", fatherName: "Sardar Amarjit Singh Dhillon", fatherOccupation: "Retired Bank Manager", motherName: "Sardarni Harjeet Kaur", motherOccupation: "Retired Teacher", siblings: "1 Sister (Married, USA)", familyType: "Nuclear", familyStatus: "Upper Middle Class", familyCity: "Phase 7, Mohali", phone: "9872112233", email: "maninder.dhillon.tech@gmail.com", whatsapp: "9872112233", partnerPref: "Well-educated professional girl. B.Tech/Doctor/CA. Age 24-29. Tricity or NRI.", consent: true, privacyLevel: "registered" },
];

let count = 0;
for (const p of profiles) {
  db.createProfile(p);
  count++;
}
console.log(`Seeded ${count} profiles.`);
